### ISSUE TITLE
Sending attachment returns ElementNotInteractableException

### ISSUE THREAD

**Issue by szb37** [dimkouv/protonmail-cli#17]
hey,

just wanted to let you know that I get the following error when I try to send a mail with attachment

b

---------------------------------------------------------------------------
ElementNotInteractableException           Traceback (most recent call last)
<ipython-input-19-7cf0bc672847> in <module>()
----> 1 client.send_mail([email], 'Missing data', message, attachments=['/media/sf_vm_share/mcrds/reports/test.txt'])

~/anaconda3/lib/python3.7/site-packages/protonmail/core.py in send_mail(self, to, subject, message, as_html, attachments)
    275             variables.element_send_mail['to_field_css'])
    276         for address in to:
--> 277             el.send_keys(address + ";")
    278             time.sleep(0.2)
    279 

~/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py in send_keys(self, *value)
    477         self._execute(Command.SEND_KEYS_TO_ELEMENT,
    478                       {'text': "".join(keys_to_typing(value)),
--> 479                        'value': keys_to_typing(value)})
    480 
    481     # RenderedWebElement Items

~/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py in _execute(self, command, params)
    631             params = {}
    632         params['id'] = self._id
--> 633         return self._parent.execute(command, params)
    634 
    635     def find_element(self, by=By.ID, value=None):

~/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py in execute(self, driver_command, params)
    319         response = self.command_executor.execute(driver_command, params)
    320         if response:
--> 321             self.error_handler.check_response(response)
    322             response['value'] = self._unwrap_value(
    323                 response.get('value', None))

~/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py in check_response(self, response)
    240                 alert_text = value['alert'].get('text')
    241             raise exception_class(message, screen, stacktrace, alert_text)
--> 242         raise exception_class(message, screen, stacktrace)
    243 
    244     def _value_or_default(self, obj, key, default):

ElementNotInteractableException: Message: Element <input id="autocompletept93dtebbmdc-1559180052784" class="autocompleteEmails-input no-outline" name="autocomplete"> is not reachable by keyboard

**Comment by dimkouv** [comment]
@balazs1987  Thanks for reporting, I'll fix it in the following days. I believe that this is happening because 'send' is triggered before the upload is completed.

**Comment by szb37** [comment]
great!

**Comment by dimkouv** [comment]
Hi @balazs1987 Sorry for the delay, Just checked and everything works as expected. As I see from the error stack (in case you haven't applied any changes) you do not have the latest version. Please try re-installing and check if it gets fixed.

**Comment by szb37** [comment]
great, thank you for your work, will make sure to update before testing it sometime next week
