### ISSUE TITLE
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-l46eq931/

### ISSUE THREAD

**Issue by xanto521** [dimkouv/protonmail-cli#18]
[root@localhost ~]# pip3 install git+https://github.com/dimkouv/protonmail-cli
Collecting git+https://github.com/dimkouv/protonmail-cli
  Cloning https://github.com/dimkouv/protonmail-cli to /tmp/pip-req-build-l46eq931
  Running command git clone -q https://github.com/dimkouv/protonmail-cli /tmp/pip-req-build-l46eq931
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-l46eq931/setup.py", line 3, in <module>
        from protonmail import metadata
      File "/tmp/pip-req-build-l46eq931/protonmail/__init__.py", line 1, in <module>
        from . import core, interactive, settings, utilities, variables, mail, metadata
      File "/tmp/pip-req-build-l46eq931/protonmail/core.py", line 7, in <module>
        from bs4 import BeautifulSoup
    ModuleNotFoundError: No module named 'bs4'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-l46eq931/

**Comment by dimkouv** [comment]
@a66298458 thanks for reporting I'll fix it this week.

A quick workaround for now is to run the following
```bash
git clone https://github.com/dimkouv/protonmail-cli
cd protonmail-cli
pip install -r requirements.pip
pip install .
```

**Comment by xanto521** [comment]
> @ a66298458感谢您的报道我将在本周修复它。
> 
> 现在快速解决方法是运行以下操作
> 
> ```shell
> git clone https://github.com/dimkouv/protonmail-cli
>  cd protonmail-cli 
> pip install -r requirements.pip 
> pip install 。
> ```

ok i'll try it

**Comment by xanto521** [comment]
Do I have to install firefox in linux?

**Comment by dimkouv** [comment]
Yes.

*I'm also going add support for chromium later.*

**Comment by dimkouv** [comment]
@a66298458 fixed
