### ISSUE TITLE
Crash on client.has_new_mail()

### ISSUE THREAD

**Issue by willbelr** [dimkouv/protonmail-cli#21]
My account has 4 messages, all unread.

Code:
```
#!/usr/bin/python3
import protonmail

client = protonmail.core.ProtonmailClient()
client.login("", "")
mails = client.get_mails("inbox")
spam = client.get_mails("spam")
has_new_mail = client.has_new_mail()
client.destroy()
```
Output:
> [INFO] 2019-06-20 06:01:27: Initiating ProtonMail client
[INFO] 2019-06-20 06:01:29: Logging in...
[INFO] 2019-06-20 06:01:39: Logged in successfully
[INFO] 2019-06-20 06:02:00: Opening https://mail.protonmail.com/spam
[INFO] 2019-06-20 06:02:23: Opening https://mail.protonmail.com/inbox
Traceback (most recent call last):
  File "/home/user/.local/share/scripts/proton/pyScript.py", line 8, in <module>
    has_new_mail = client.has_new_mail()
  File "/usr/lib/python3.7/site-packages/protonmail/core.py", line 282, in has_new_mail
    for m in mails:
TypeError: 'NoneType' object is not iterable

**Comment by chadfurman** [comment]
Same:

```
Traceback (most recent call last):
  File "/usr/bin/protonmail-cli", line 159, in <module>
    args.func(args)
  File "/usr/bin/protonmail-cli", line 19, in subcommand_check
    if client.has_new_mail():
  File "/opt/protonmail-cli/protonmail/core.py", line 282, in has_new_mail
    for m in mails:
TypeError: 'NoneType' object is not iterable
```

**Comment by chadfurman** [comment]
After changing conversation-list-columns to conversation-list-rows in the ~settings~ variables file, it stopped crashing but can't find mails.  I'm guessing the HTML on the site changed.

**Comment by chadfurman** [comment]
After changing "conversation-meta" to "conversation" in the variables.py file, the script started to work for me.

**Comment by dimkouv** [comment]
Sorry for the delay, I'll work on it this weekend

**Comment by dimkouv** [comment]
@chadfurman  You're right, some HTML was changed. I updated the selector variables and it works as expected now.
