### ISSUE TITLE
E-mails can't be sent without attacment

### ISSUE THREAD

**Issue by Arkoprovo1996** [dimkouv/protonmail-cli#23]
I try
`protonmail-cli --credential creds.ini s -t "xxxxxxxxxx@xxxx.xxx" -s "test" -b "fuck off"`
It doesn't get sent, but I add an attachment via the `-a` flag & it does smoothly

**Comment by dimkouv** [comment]
@Arkoprovo1996 I'll check it

**Comment by dimkouv** [comment]
@Arkoprovo1996 It appears to be working on my side, try updating your geckodriver, I updated the url on README.md.
