### ISSUE TITLE
Use --headless command line argument to remove dependency on pyvirtualdisplay

### ISSUE THREAD

**Issue by x11x** [dimkouv/protonmail-cli#25]
Hi,
Just curious (haven't looked into it much so I could be wrong): is the `pyvirtualdisplay` dependency really needed? Firefox provides a `--headless` argument for this kind of use case.
I found an example of [using Firefox with Selenium on stackoverflow](https://stackoverflow.com/a/52700598) which looks pretty simple.
Removing the pyvirtualdisplay dependency should allow full Windows support too, I think?

**Comment by dimkouv** [comment]
@x11x Thank you and sorry for the delay. I'll give it a try.
