### ISSUE TITLE
Error: AttributeError: 'NoneType' object has no attribute 'current_url'

### ISSUE THREAD

**Issue by RealStJimmy** [dimkouv/protonmail-cli#26]
When ever I log into the system and type Inbox it throws this error: 

``Traceback (most recent call last):
  File "protonmail-cli.py", line 163, in <module>
    session.start()
  File "/opt/protonmail-cli/protonmail/interactive.py", line 160, in start
    options[choice]["function"]()  # call the anonymous function that is attached on menu choice
  File "/opt/protonmail-cli/protonmail/interactive.py", line 135, in <lambda>
    "function": lambda: self.show(opt)
  File "/opt/protonmail-cli/protonmail/interactive.py", line 103, in show
    for mail in self.client.get_mails(page):
  File "/opt/protonmail-cli/protonmail/core.py", line 157, in get_mails
    if self.web_driver.current_url != url:
AttributeError: 'NoneType' object has no attribute 'current_url'
``

**Comment by dimkouv** [comment]
@RealStJimmy  What is the output you get after running `geckodriver -V` ?

**Comment by RealStJimmy** [comment]
`geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000`

Did I make a dumb mistake?

**Comment by dimkouv** [comment]
I thought that you didn't have geckodriver in your path but it looks like you have it.
Can you try listing your inbox with: `./protonmail-cli.py l -t inbox` the error will be printed if you do it like this. I'll have to improve the *interactive session* to print out any errors.

**Comment by RealStJimmy** [comment]
Now i get 
`TypeError: __init__() got an unexpected keyword aliases`

**Comment by dimkouv** [comment]
What is the version of your python interpreter?
`python --version`

**Comment by RealStJimmy** [comment]
Just realized i ran the above in python2  

After running in python3 I get this error 

`[INFO] 2020-02-09 21:14:52: Initiating ProtonMail client
[INFO] 2020-02-09 21:14:52: Unable to initiate Protonmail Client. Reason: [Errno 13] Permission denied: 'geckodriver.log'
[INFO] 2020-02-09 21:14:52: Client is not initialized
Traceback (most recent call last):
  File "protonmail-cli.py", line 159, in <module>
    args.func(args)
  File "protonmail-cli.py", line 13, in subcommand_list
    for mail in client.get_mails(args.type):
  File "/opt/protonmail-cli/protonmail/core.py", line 157, in get_mails
    if self.web_driver.current_url != url:
AttributeError: 'NoneType' object has no attribute 'current_url'
`

after running with sudo i get this error

[INFO] 2020-02-09 21:15:33: Initiating ProtonMail client
[INFO] 2020-02-09 21:15:34: Unable to initiate Protonmail Client. Reason: Message: invalid argument: can't kill an exited process

[INFO] 2020-02-09 21:15:34: Client is not initialized
Traceback (most recent call last):
  File "protonmail-cli.py", line 159, in <module>
    args.func(args)
  File "protonmail-cli.py", line 13, in subcommand_list
    for mail in client.get_mails(args.type):
  File "/opt/protonmail-cli/protonmail/core.py", line 157, in get_mails
    if self.web_driver.current_url != url:
AttributeError: 'NoneType' object has no attribute 'current_url'

**Comment by dimkouv** [comment]
You've probably ran this tool as root the first time and the file `geckodriver.log` was created by root, so you don't have permission now to write it as a normal user.

You can find where this file is
`sudo find / -name geckodriver.log` and then change the owner to your user `sudo chown username:username geckodriver.log`

**Comment by RealStJimmy** [comment]
Thanks man that solved it.
