### ISSUE TITLE
configparser not found

### ISSUE THREAD

**Issue by Questium** [dimkouv/protonmail-cli#34]
File "/bin/protonmail-cli", line 3, in <module> import configparser ImportError: No module named configparser

what do i need to install?

**Comment by dimkouv** [comment]
@Banemus  You should use python3

**Comment by Banemus** [comment]
@dimkouv 
python3 --version

gives me

python 3.6.9

Just trying to use command line to do protonmail-cli --help and then I get that error.

So not sure how I should say the system to use python3
